### ISSUE TITLE
Compile questions

### ISSUE THREAD

**Issue by Rwellchan** [googlecreativelab/anypixel#20]
Regarding the controller firmware, we encountered a problem when compiling "project_config.c"  mentioning the macro defenition #ifdef REV1 has to be defined but couldn't seen from any of the files. According to the REV number on the PCB board is 3 rather than 1. Is this a versioning problem or can anyone help? Thanks. The files are downloaded offline directly from the repository. Thanks.
![472408612459670697](https://cloud.githubusercontent.com/assets/23549098/20422081/1887e870-ada3-11e6-983f-9f57868a2d4c.jpg)

**Comment by ajiblock** [comment]
This is a structure we used to allow for changes in pinouts or connected components as a PCB is revised, but it isn't really necessary for this project, so it didn't get updated with different rev numbers.  

You can just add the following:
-DREV1 in the compiler flags for your project.  
-You must be using a different build environment since the .ebp project file does have a -DREV1 compiler flag in it.
